### ISSUE TITLE
License change from GPL to MIT

### ISSUE THREAD

**Issue by gabipurcaru** [cinely/mule-uploader#62]
This is a very important notice, and I will need an answer from *ALL* the contributors.

@kookster, @Flynsarmy, @H-Max, @davelassanske, @keithzg, @couresel, @tuler and @cinely:

Do you approve that the code you contributed to this project, Mule Uploader, changes the license from [GPL](http://www.gnu.org/licenses/gpl-3.0.en.html) to [MIT](https://opensource.org/licenses/MIT)?

I need a written consent from all of you, so please reply to this issue. If you don't consent to the change, please let me know, as I will have to remove your contributions from the codebase. For more information about what this means, read this: http://stackoverflow.com/questions/3902754/mit-vs-gpl-license.

**Comment by gabipurcaru** [comment]
Of course, I consent to this.

If you need more info on why changing the license is needed, please read #57.

**Comment by davelassanske** [comment]
I consent to this change in license.

**Comment by Flynsarmy** [comment]
I consent

**Comment by H-Max** [comment]
I consent too

**Comment by kookster** [comment]
I consent to the license change to MIT.

- Andrew

**Comment by couresel** [comment]
I consent to this.

I take it the catalyst was more permissive distribution rights for projects
utilizing this source.

**Comment by david542542** [comment]
I consent.

**Comment by cinely** [comment]
I consent.

- David

**Comment by gabipurcaru** [comment]
Thanks for the support everyone! @keithzg and @tuler, please give us your input.

**Comment by tuler** [comment]
I consent

**Comment by abuisine** [comment]
I consent as well !

**Comment by gabipurcaru** [comment]
Thanks everyone! Unfortunately I've had to revert @keithzg's changes since he didn't respond (it was just a typo fix fortunately -- not sure whether that can be copyrighted but nevertheless I've decided to leave the typo in there for now just to be one the same side).

I've created #64 which changes the license. Please let me know if you see any problems with it. If everything's fine, I'll merge it in one or two days.

**Comment by couresel** [comment]
FYI, you can change the word/variable all together to something synonymous
:)

Thanks for all the hard work.

**Comment by gabipurcaru** [comment]
It is done, thanks for all the help everyone!

@couresel, yes, definitely, good point.

**Comment by keithzg** [comment]
The typo fix is almost certainly not copywriteable, and in fact the FSF's guidance on small pieces of documentation, even when it's code being included in the documentation, is that this is okay: http://www.gnu.org/licenses/gpl-faq.en.html#SourceCodeInDocumentation

So I frankly don't have to have given you the permission, but if you're so scared of the GPL that you think I gotta, then you have my permission :)
